// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlakDukkani.DAL;

#nullable disable

namespace PlakDukkani.DAL.Migrations
{
    [DbContext(typeof(PlakDukkaniContext))]
    partial class PlakDukkaniContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlakDukkani.Entities.Concrete.Admin", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            ID = new Guid("b7542ff7-f63a-401e-95fa-d4f7facd2f6f"),
                            CreatedDate = new DateTime(2023, 1, 29, 16, 5, 52, 648, DateTimeKind.Local).AddTicks(1556),
                            KullaniciAdi = "Admin1234",
                            ModifiedDate = new DateTime(2023, 1, 29, 16, 5, 52, 648, DateTimeKind.Local).AddTicks(1567),
                            Sifre = "6CDE6915D987CA57A7C808D0BF71105FF1AE67697421C55471B5ABFA303ED5B3"
                        },
                        new
                        {
                            ID = new Guid("7ba9c9d4-b354-4951-987a-e3a130d743cb"),
                            CreatedDate = new DateTime(2023, 1, 29, 16, 5, 52, 648, DateTimeKind.Local).AddTicks(1905),
                            KullaniciAdi = "Admin123456",
                            ModifiedDate = new DateTime(2023, 1, 29, 16, 5, 52, 648, DateTimeKind.Local).AddTicks(1906),
                            Sifre = "6CDE6915D987CA57A7C808D0BF71105FF1AE67697421C55471B5ABFA303ED5B3"
                        });
                });

            modelBuilder.Entity("PlakDukkani.Entities.Concrete.Album", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlbumAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndirimOrani")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sanatci")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("SatisDurumu")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            ID = new Guid("7fff5d91-b6b9-4728-ba93-17a1261553d2"),
                            AlbumAdi = "abc",
                            CikisTarihi = new DateTime(2023, 1, 29, 16, 5, 52, 648, DateTimeKind.Local).AddTicks(2018),
                            CreatedDate = new DateTime(2023, 1, 29, 16, 5, 52, 648, DateTimeKind.Local).AddTicks(2020),
                            Fiyat = 100m,
                            IndirimOrani = 10m,
                            ModifiedDate = new DateTime(2023, 1, 29, 16, 5, 52, 648, DateTimeKind.Local).AddTicks(2021),
                            Sanatci = "abc",
                            SatisDurumu = true
                        },
                        new
                        {
                            ID = new Guid("5a4fc427-188a-46e9-8e1a-28930c8a5215"),
                            AlbumAdi = "Melek",
                            CikisTarihi = new DateTime(2023, 1, 29, 16, 5, 52, 648, DateTimeKind.Local).AddTicks(2027),
                            CreatedDate = new DateTime(2023, 1, 29, 16, 5, 52, 648, DateTimeKind.Local).AddTicks(2028),
                            Fiyat = 100m,
                            IndirimOrani = 10m,
                            ModifiedDate = new DateTime(2023, 1, 29, 16, 5, 52, 648, DateTimeKind.Local).AddTicks(2028),
                            Sanatci = "Melek Melek",
                            SatisDurumu = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
